### ISSUE TITLE
travis-ci integration doesn't work as expected

### ISSUE THREAD

**Issue by dasrick** [dasrick/go-teams-notify#13]

**Comment by atc0005** [comment]
I'm guessing that this is related to the lack of golantci-lint warnings for #11 (which you had to handle in #12)?

**Comment by atc0005** [comment]
Some questions below to potentially help trigger an "ah ha!" moment (those are great).

---

Are these lines the issue?

https://github.com/dasrick/go-teams-notify/blob/823a70e950d37f46770bfcfceb6418d7a8a12741/.travis.yml#L22-L24

Should they instead be the following (note the colons)?

```yaml
after_success:
  - if: if [[ $TRAVIS_GO_VERSION == 1.14* ]]; $GOPATH/bin/goveralls -service=travis-ci ; fi
  - if: if [[ $TRAVIS_GO_VERSION == 1.14* ]]; bash <(curl -s https://codecov.io/bash) ; fi
```

Was this working after the changes in 257c4b5bcf0eb0e3fbeb161402dd5a64a5cd0cbb?
